services:

  database:
    image: postgres
    volumes:
      - ./pg_data/:/usr/src/app
    ports:
      - 5432:5432
    container_name: blogs-pg
    environment:
      - POSTGRES_PASSWORD=pw
      - POSTGRES_USER=user
      - POSTGRES_DB=blogs

  server:
    depends_on:
      - database
    image: blogs-server
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3001
    container_name: blogs-backend
    environment:
      - DATABASE_URL=postgres://user:pw@blogs-pg:5432/blogs