name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-20.04
    env:
      working-directory: ./part11/full-stack-open-pokedex
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
          working-directory: ./part11/full-stack-open-pokedex

  deploy:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}
    needs: checks
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{vars.HEROKU_APP_NAME}}
          heroku_email: ${{vars.HEROKU_EMAIL}}
          appdir: part11/full-stack-open-pokedex
          dontuseforce: false 
          healthcheck: https://${{vars.HEROKU_APP_NAME}}.herokuapp.com/health
          checkstring: ok
          rollbackonhealthcheckfailed: true

  tag_release:
    runs-on: ubuntu-20.04
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch